account_screen / fix display data when call api info user
awesome-academy/Book-shop pull request #4
Opened 2022-10-19 07:27 UTC by hungvv-1301

## Related Tickets
- [#Task #54665: Create View Layout Account](https://edu-redmine.sun-asterisk.vn/issues/54665)
- [#Task #54666: Create Logic Layout Account](https://edu-redmine.sun-asterisk.vn/issues/54666)
- [#Task #54667: Display profile ](https://edu-redmine.sun-asterisk.vn/issues/54667)
## WHAT
- 
## Evidence (Screenshot or Video)

## Review Checklist

Category | View Point | Description | Self review | Reviewer2 (name)
--- | --- | --- | --- | ---
Conventions | Sun* coding conventions | https://sal.vn/WtYPAy |<li>- [ ] yes</li>|<li>- [ ] yes</li>  
Conventions | Kotlin coding conventions | https://kotlinlang.org/docs/coding-conventions.html |<li>- [ ] yes</li>|<li>- [ ] yes</li>  
Redmine | Sun* Redmine working process  | https://sal.vn/piPoQn |<li>- [ ] yes</li>|<li>- [ ] yes</li>  

## Notes (Optional)
*(Impacted Areas in Application(List features, api, models or services that this PR will affect))*

*(List gem, library third party add new)*

*(Other notes)*

2022-10-19 08:22 UTC, cuongvd-1287 commented on app/src/main/res/drawable/bg_header_account_fragment.xml
> +</shape>
end line nhá

2022-10-19 08:23 UTC, cuongvd-1287 commented on app/src/main/res/drawable/ic_help_24dp.xml
> +</vector>
.

2022-10-19 08:23 UTC, cuongvd-1287 commented on app/src/main/res/drawable/ic_ring_24dp.xml
> +</vector>
.

2022-10-19 08:23 UTC, cuongvd-1287 commented on app/src/main/res/drawable/ic_statistical_24dp.xml
> +</vector>
.

2022-10-19 09:33 UTC, daolq-2712 requested changes
Pls check my comments!

2022-10-19 09:33 UTC, daolq-2712 commented on app/src/main/AndroidManifest.xml
> +            android:noHistory="true" />
App này support xoay màn hình à em?

2022-10-19 09:33 UTC, daolq-2712 commented on app/src/main/java/com/atom/android/bookshop/ui/account/AccountPresenter.kt
> +        // late impl
```suggestion
        // TODO implement later
```
Sửa hết cho mấy chỗ khác em nhé!

vì sao cmt như này em đọc ở đây: https://www.jetbrains.com/help/idea/using-todo.html

2022-10-19 09:33 UTC, daolq-2712 commented on app/src/main/res/drawable/bg_header_account_fragment.xml
> +</shape>
```suggestion
</shape>

```

2022-10-19 09:33 UTC, daolq-2712 commented on app/src/main/res/drawable/ic_help_24dp.xml
> +</vector>
```suggestion
</vector>

```

2022-10-19 09:33 UTC, daolq-2712 commented on app/src/main/res/drawable/ic_ring_24dp.xml
> +</vector>
```suggestion
</vector>

```

2022-10-19 09:33 UTC, daolq-2712 commented on app/src/main/res/drawable/ic_statistical_24dp.xml
> +</vector>
```suggestion
</vector>

```

2022-10-19 09:38 UTC, hungvv-1301 commented on app/src/main/AndroidManifest.xml
> +            android:noHistory="true" />
em set portrain lại ạ

2022-10-20 01:34 UTC, vietnh-1109 commented on app/src/main/java/com/atom/android/bookshop/ui/main/MainActivity.kt
> +        const val POSITION_FRAGMENT_ACCOUNT = 3
ko dùng đâu nữa thì để private đi e

2022-10-20 01:35 UTC, vietnh-1109 commented on app/src/main/res/layout/fragment_account.xml
> +
remove

2022-10-20 01:43 UTC, hungvv-1301 commented on app/src/main/java/com/atom/android/bookshop/ui/main/MainActivity.kt
> +        const val POSITION_FRAGMENT_ACCOUNT = 3
Dạ có dùng ở ngoài class ạ

2022-10-20 02:42 UTC, merged